apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name}}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.capacity.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ .Values.hostPath.path }}"
    type: {{ .Values.hostPath.type }}