apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regscale-local.secretName" . }}
  labels:
    {{- include "regscale-local.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWTSecretKey: "{{ .Values.secret.jwtSecretKey }}"
  SQLConn: "{{ .Values.secret.dbConnectionString }}"
  EncryptionKey: "{{ .Values.secret.encryptionKey }}"